### ISSUE TITLE
jobDescriptions empty

### ISSUE THREAD

**Issue by t-bittner** [SammyTheSalmon/personio#1]
Hello, 
after installing and configuring the extension, I currently have the problem that the jobDescriptions field is not populated.

However, in the Personio XML, this field is populated.
Excerpt of the XML:
```
<position>
<id>123451</id>
<office>München</office>
<department>Test Department</department>
<recruitingCategory>Festangestellte</recruitingCategory>
<name>Teststelle (w/m/d)</name>
<jobDescriptions>
<jobDescription>
<name>Ihre Aufgaben</name>
<value>
<![CDATA[ Lorem ipsum dolor it samet ]]>
</value>
</jobDescription>
<jobDescription>
<name>Ihr Profil</name>
<value>
<![CDATA[ Lorem ipsum dolor it samet ]]>
</value>
</jobDescription>
<jobDescription>
<name>Warum wir?</name>
<value>
<![CDATA[ Lorem ipsum dolor it samet ]]>
</value>
</jobDescription>
<jobDescription>
<name>Ansprechpartner</name>
<value>
<![CDATA[ Lorem ipsum dolor it samet ]]>
</value>
</jobDescription>
</jobDescriptions>
<employmentType>permanent</employmentType>
<seniority>experienced</seniority>
<schedule>full-time</schedule>
<yearsOfExperience>2-5</yearsOfExperience>
<keywords>Lorem,Ipsum,Dolor,München</keywords>
<occupation>general_and_other_medical_and_health</occupation>
<occupationCategory>medical_and_health</occupationCategory>
<createdAt>2022-04-06T09:51:30+00:00</createdAt>
</position>
```

What can/must I adjust to get all job relevant information on the detail page?

Best regards
T.Bittner

**Comment by SammyTheSalmon** [comment]
Hello T. Bittner, 

I have reviewed your issue with the newest version 0.1.7 and I could not find any problem.

As you can see in the debug output, the descriptions are passed to the template.

![image](https://user-images.githubusercontent.com/2017543/180459010-0654b28e-80c1-4111-b7d9-e11a4a721c11.png)

Which version do you use?
Did you use the Standard template `personio/Resources/Private/Templates/Show.html`?


The following snippet is included for the output of the descriptions: 
```    
        <div class="descriptions">
          <f:translate key="label.jobDescription" />
          <f:for each="{item.jobDescriptions.jobDescription}" as="jobDescription" iteration="iterator">
            <div class="description description-{iterator.cycle}">
              <h3>{jobDescription.name}</h3>
              {jobDescription.value -> f:format.raw()}
            </div>
          </f:for>
        </div>
```

Best regards
P. Koschella

**Comment by t-bittner** [comment]
Hello, 
yes I also use version 0.1.7 and also the default template from the extension.

After reinstallation and reconfiguration, the jobDescriptions are now also output.

best thanks
